# Generated by Django 2.2.2 on 2019-06-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='coverimg',
            field=models.URLField(default='https://ss1.bdstatic.com/70cFuXSh_Q1YnxGkpoWK1HF6hhy/it/u=891209561,3636218284&fm=27&gp=0.jpg', verbose_name='封面图片'),
        ),
    ]
