# Generated by Django 2.2.2 on 2019-06-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_article_coverimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='xx@xx.com', max_length=254),
        ),
    ]
